### ISSUE TITLE
BrushBuilder::build() should use .view_formats of configuration, not .format

### ISSUE THREAD

**Issue by khyperia** [Blatko1/wgpu-text#11]
The way to enable an SRGB output on webgpu is a bit odd: Bgra8UnormSrgb is not supported by the webgpu backend (unlike most desktop wgpu apps), but Bgra8Unorm is. The intended way to get an SRGB output is to pass in the SRGB version of the format in SurfaceConfiguration.view_formats to Surface::configure, and the non-SRGB version in SurfaceConfiguration.format (unlike in desktop apps, where those two formats are frequently the same), then in the render loop, pass in TextureViewDescriptor.format = the SRGB format into the render texture's create_view function.

Anyway, point is, with this wacky webgpu SRGB setup, wgpu-text's internal pipelines should be using the SRGB versions of the format, not the non-SRGB versions, i.e. BrushBuilder::build() should pull from SurfaceConfiguration.view_formats instead of SurfaceConfiguration.format. Thankfully there's a easy workaround in wgpu-text and I'm simply calling BrushBuilder.build_custom(width, height, the_SRGB_format) and it works great, but it'd be awesome if it "worked out of the box" when using BrushBuilder.build()!

https://github.com/Blatko1/wgpu-text/blob/fb715978a2156834f39c6ccedb7c5aafc72aad6a/src/brush.rs#L337-L343

**Comment by Blatko1** [comment]
Thanks for taking the time to bring attention to this.This could be an issue for some users. However, the other day I found [this](https://github.com/gfx-rs/wgpu/wiki/Encapsulating-Graphics-Work#new) in the *wgpu wiki*, where they recommend accepting only a `TextureFormat`, `width`, and `height`.
Accordingly, I will remove the BrushBuilder.build() function entirely in the next version of the library (probably v0.8.0).
