### ISSUE TITLE
Types of `glyph_brush` in public API: either reexport the crate or wrap everything

### ISSUE THREAD

**Issue by LukasKalbertodt** [Blatko1/wgpu-text#14]
Thanks for this library!

I noticed that quite a few APIs of this crate use types from `glyph_brush`. That makes it a public dependency of `wgpu_text` and as such, this crate should `pub use glyph_brush` at the crate root. That way a user can say `wgpu_text::glyph_brush::Font` for example. Right now the only way to do that is to add `glyph_brush` as a dependency myself, but then I might easier run into version mismatches between the crate. 

This would also fix rustdoc not linking those. Generally, I think one should avoid situations in which rustdoc does not link types or traits. Then there is usually something fishy going on.

Thanks!

**Comment by Blatko1** [comment]
Thank you for your suggestion!

You're right that it should be a public dependency of *wgpu_text*. On the other hand, I wonder why I reexported each type manually instead of making it public. Also, thank you for noting about the *rustdoc* not linking.

I'll make the necessary changes.
