### ISSUE TITLE
How to prevent brush lifetime specifier

### ISSUE THREAD

**Issue by kaphula** [Blatko1/wgpu-text#16]
Hello,

I am stuck with the brush struct since its type needs explicit lifetime annotation if I want to store the brush's value inside another struct. In my case, I cannot add lifetime specifier to the wrapper struct (`FontRendering`). Is there a way to not have to use type that requires lifetime specifier? `wgpu_glyph`'s brush did not require lifetime specifier as the font was initialized using `FontArc` (https://github.com/hecrj/wgpu_glyph/blob/master/examples/hello.rs#L57)

```rust

       struct FontRendering  {
               brush: TextBrush<FontRef> // error, lifetime needed!
        }

        // ...

        let inconsolata = include_bytes!(
            "../../assets/Inconsolata-Regular.ttf"
        );

        let mut brush =
            BrushBuilder::using_font_bytes(inconsolata).unwrap()
            .build(&engine.device, engine.config.width, engine.config.height, engine.config.format);

        let font_rendering = FontRendering {
            brush: brush

        };


```

**Comment by Blatko1** [comment]
In a few moments, I will release a new version, 0.8.2, which reexports `glyph_brush` so you can import the `FontArc` in your code and do everything as in the link you provided.
