### ISSUE TITLE
External render data approach

### ISSUE THREAD

**Issue by PPakalns** [Blatko1/wgpu-text#17]
https://github.com/gfx-rs/wgpu/wiki/Encapsulating-Graphics-Work

External Render Data
```rs
impl MiddlewareRenderer {
    fn new(&Device, &TextureFormat, ..) -> Self;

    // Prepare for rendering, create all resources used during render, storing render data in PerFrameData
    fn prepare(&self, ..) -> PerFrameData; 

    // Render using data in PerFrameData and user provided renderpass
    fn render<'rpass>(&'rpass self, &mut RenderPass<'pass>, &'rpass PerFrameData); 
}
```
Internal Render Data
```rs
impl MiddlewareRenderer {
    fn new(&Device, &TextureFormat, ..) -> Self;

    // Prepare for rendering, create all resources used during render, storing render data internally
    fn prepare(&mut self, ..);

    // Render using internal data and user provided renderpass
    fn render<'rpass>(&'rpass self, &mut RenderPass<'rpass>);
}
```

This library uses internal render data approach which requires
&'pass mut self access to TextBrush:
https://docs.rs/wgpu_text/latest/wgpu_text/struct.TextBrush.html#method.draw

In a lot of cases wgpu rendering can be done through other libraries that use External Render data approach for which data modification can be done only in prepare part and in rendering part all data except RenderPass is immutable.

Which causes problem with draw call in TextBrush!

One example is egui_wgpu integration:
https://docs.rs/egui-wgpu/latest/egui_wgpu/renderer/struct.CallbackFn.html
https://github.com/emilk/egui/blob/master/crates/egui_demo_app/src/apps/custom3d_wgpu.rs#L145

That allows to paint specific parts of GUI manually with wgpu. 

It uses External render data approach and brush is available only as immutable reference.  If I try to use Mutex and other mechanisms to retrieve it in mutable way its lifetime is not long enough (need 'rpass).

Is it possible to use this library in this use case? How to do that?

Additionally, is it possible to reuse some parts of TextBrush (font texture?) for drawing multiple times in one renderpass.

Maybe draw call could be immutable?
It looks like https://github.com/gfx-rs/wgpu/wiki/Encapsulating-Graphics-Work documentation is inconsistent.
Opened issue: https://github.com/gfx-rs/wgpu/issues/3953

**Comment by Blatko1** [comment]
Thank you for creating this issue and providing information. I see that you fixed the mutable draw call problem yourself. Additionally, from what you wrote, I understand that switching to the `External Render Data` API design would fix some of the problems you have stated. Library users could then store some rarely used non-changing `PerFrameData` (text vertex buffers) and use it only when needed and, at the same time, update constantly changing GUI text and render it every frame. The v0.9.0 will probably be the version where I implement the `External Render Data` API design.

**Comment by Blatko1** [comment]
Sadly, the `External Render Data` API design cannot be implemented because every time queued text gets processed, the inner texture cache changes meaning the texture coordinates of any past text buffers are now possibly incorrect.
For drawing multiple times in one `RenderPass`, I'll try adding a larger `RenderQueue`, which would then be processed by the `draw()` function, which would then call a *wgpu* draw function for each element.

**Comment by Blatko1** [comment]
Maybe I'll be able to implement the `External Render Data` API design by storing the texture data and applying it whenever the user renders the text again. It could reduce the performance, but it would work. I'll split the project into **internal data** API design and **external data** API design. The default would be the *internal data* API design, and if you would like to use the *external data* API design, users would need to specify the feature flag.

**Comment by Blatko1** [comment]
Probably my final comment:
I give up on implementing the `External Redner Data` design because of complicated texture caching, and trying to retain the draw function being non-mutable is hard. I'll just add a new draw function for making multiple draw calls in one render pass and not bother with making things non-mutable.

**Comment by Blatko1** [comment]
I give up. Having multiple draw calls in one render pass is impossible without degrading performance with multiple buffers and complicated additional logic. Most problems are caused by the `glyph_brush` crate, which is made explicitly for rendering everything in one draw call.

**Comment by PPakalns** [comment]
@Blatko1  Thank you for looking into this.
